public enum Process {
    START,
    CREATE_FRAME,
    ATTACH_DOORS,
    GALVANIZE_FRAME,
    DUST_OFF,
    SPRAY_PAINT,
    APPLY_VARNISH,
    HAND_WAX,
    FASHION_ENGINE,
    LOWER_TO_POWER_TRAIN,
    INSTALL_WHEELS,
    INSTALL_DASHBOARD,
    INSTALL_STEERING_WHEEL,
    INSTALL_TRUNK,
    RELEASE
}
